#!/usr/bin/env bash
# Fix the container to run nginx as the nginx user on port 8080
sed -i 's/user www-data;/user nginx;/g' /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-enabled/default
service nginx restart
