#!/usr/bin/env bash
# Configure UFW to block all incoming traffic except 22, 80, and 443 TCP ports
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp
sudo ufw --force enable

