import { useState, useEffect, useCallback } from 'react';
import { supabase } from '@/integrations/supabase/client';

export interface Employee {
  id: string;
  employee_number: string;
  full_name: string;
  email: string | null;
  phone: string | null;
  department_id: string | null;
  position_id: string | null;
  date_of_birth: string | null;
  hire_date: string;
  employment_status: string;
  employment_type: string;
  gender: string | null;
  address: string | null;
  emergency_contact_name: string | null;
  emergency_contact_phone: string | null;
  avatar_url: string | null;
  notes: string | null;
  linked_user_id: string | null;
  created_by: string | null;
  created_at: string;
  updated_at: string;
  // joined
  department_name?: string;
  position_name?: string;
}

export interface EmployeeInsert {
  full_name: string;
  email?: string;
  phone?: string;
  department_id?: string | null;
  position_id?: string | null;
  date_of_birth?: string | null;
  hire_date?: string;
  employment_status?: string;
  employment_type?: string;
  gender?: string | null;
  address?: string | null;
  emergency_contact_name?: string | null;
  emergency_contact_phone?: string | null;
  notes?: string | null;
}

export function useEmployees() {
  const [employees, setEmployees] = useState<Employee[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<Error | null>(null);

  const fetchEmployees = useCallback(async () => {
    setLoading(true);
    try {
      const { data, error: fetchError } = await supabase
        .from('employees')
        .select(`
          *,
          departments (name),
          positions (name)
        `)
        .order('full_name');

      if (fetchError) throw fetchError;

      const mapped: Employee[] = (data || []).map((e: any) => ({
        ...e,
        department_name: e.departments?.name || null,
        position_name: e.positions?.name || null,
      }));

      setEmployees(mapped);
      setError(null);
    } catch (err) {
      console.error('Error fetching employees:', err);
      setError(err instanceof Error ? err : new Error('Failed to fetch employees'));
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    fetchEmployees();
  }, [fetchEmployees]);

  const addEmployee = async (employee: EmployeeInsert) => {
    try {
      const { data: { user } } = await supabase.auth.getUser();
      const { data, error } = await supabase
        .from('employees')
        .insert({
          ...employee,
          employee_number: '', // auto-generated by trigger
          created_by: user?.id || null,
        })
        .select()
        .single();

      if (error) throw error;
      await fetchEmployees();
      return { data, error: null };
    } catch (err) {
      return { data: null, error: err instanceof Error ? err : new Error('Failed to add employee') };
    }
  };

  const updateEmployee = async (id: string, updates: Partial<EmployeeInsert>) => {
    try {
      const { error } = await supabase
        .from('employees')
        .update(updates)
        .eq('id', id);

      if (error) throw error;
      await fetchEmployees();
      return { error: null };
    } catch (err) {
      return { error: err instanceof Error ? err : new Error('Failed to update employee') };
    }
  };

  const deleteEmployee = async (id: string) => {
    try {
      const { error } = await supabase
        .from('employees')
        .delete()
        .eq('id', id);

      if (error) throw error;
      await fetchEmployees();
      return { error: null };
    } catch (err) {
      return { error: err instanceof Error ? err : new Error('Failed to delete employee') };
    }
  };

  return {
    employees,
    loading,
    error,
    refetch: fetchEmployees,
    addEmployee,
    updateEmployee,
    deleteEmployee,
  };
}
