#!/usr/bin/env bash
# Configures a new Ubuntu machine's Nginx to include a custom HTTP response header
# The header X-Served-By contains the hostname of the server
# shellcheck disable=SC2154

apt-get update
apt-get install -y nginx

# Remove any previous X-Served-By header config (idempotent)
sed -i '/add_header X-Served-By/d' /etc/nginx/sites-available/default

# Add custom header with the server hostname using Nginx $hostname variable
sed -i '/server_name _;/a \    add_header X-Served-By $hostname;' /etc/nginx/sites-available/default

service nginx restart
