#!/usr/bin/env bash
# Configures a new Ubuntu machine's Nginx to include a custom HTTP response header
# The header X-Served-By contains the hostname of the server
# shellcheck disable=SC2154

apt-get update
apt-get -y install nginx

# Add custom header with the server hostname to the Nginx default site config
HEADER="\\\tadd_header X-Served-By \$HOSTNAME;"
sed -i "s/server_name _;/server_name _;\n$HEADER/" /etc/nginx/sites-available/default

service nginx restart
