#!/usr/bin/env bash
# Installs and configures HAproxy on a new Ubuntu machine
# Distributes traffic to web-01 and web-02 using roundrobin

apt-get update
apt-get -y install haproxy

# Configure HAproxy frontend and backend
cat >> /etc/haproxy/haproxy.cfg <<EOF

frontend http_front
    bind *:80
    mode http
    default_backend http_back

backend http_back
    balance roundrobin
    server 6979-web-01 13.218.57.12:80 check
    server 6979-web-02 44.202.228.82:80 check
EOF

# Enable HAproxy to be managed via init script
sed -i 's/^ENABLED=.*/ENABLED=1/' /etc/default/haproxy

service haproxy restart

service haproxy restart
