#!/usr/bin/env bash
# Make nginx listen on port 80 by killing apache process that may be bound to it
sudo service nginx stop || true
sudo service apache2 stop || true
sudo sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default
sudo service nginx start
